services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
