services:
  mongo:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV:development
      - MONGO_DB_URI:mongodb://mongo:27017/facile
      - PORT:8000
    depends_on:
      - mongo

volumes:
  mongo-data:
